### ISSUE TITLE
Enclose map in Bootstrap container

### ISSUE THREAD

**Issue by br3ndonland** [growwithgooglema/mbtaccess#12]
The map needs to be properly situated in the Bootstrap grid. It's currently sitting outside the other containers. This will require revision of the JavaScript code for the map, so it can be positioned more flexibly. We can then add `<main>` tags and more `<div>` structure.

![screen-shot-2018-04-10-at-12 35 11-am-desktop](https://user-images.githubusercontent.com/26674818/38543865-cb1b0aac-3c73-11e8-9a21-87d9ac498a93.png)

**Comment by AbdouSeck** [comment]
@br3ndonland can you please elaborate on this a little bit? Placing the `div` element holding the map inside a `main` element can be done easily (if it won't cause any issues with how google maps `js` and `css` code renders the map). But which `javascript` code would need to be revised?

**Comment by br3ndonland** [comment]
I would be happy to elaborate @AbdouSeck . Here's the current code for the center container (with the search and map) in index.html:

```html
  <!-- TODO: main should go here -->
    <div class="container">
      <!-- Search form -->
      <div class="row p-1">
        <div class="col-md-8">
          <form class="form-inline" id="searchform">
            <fieldset id="searchbox">
              <input id="searchtxt" class="form-control" type="search" placeholder="Enter place name" aria-label="Search">
              <button id="searchbtn" class="btn btn-primary my-1">Search</button>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
    <!-- Map -->
    <div class="container" id="map"></div>
  <!-- TODO: close main tag here -->
```

If I simply add `main` tags, the map doesn't show up:

```html
  <main>
    <div class="container">
      <!-- Search form -->
      <div class="row p-1">
        <div class="col-md-8">
          <form class="form-inline" id="searchform">
            <fieldset id="searchbox">
              <input id="searchtxt" class="form-control" type="search" placeholder="Enter place name" aria-label="Search">
              <button id="searchbtn" class="btn btn-primary my-1">Search</button>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
    <!-- Map -->
    <div class="container" id="map"></div>
  </main>
```

![screen-shot-2018-04-18-at-11 44 32-am-issue-12-no-map](https://user-images.githubusercontent.com/26674818/38942989-4660146a-42fe-11e8-80da-894fc798a5b2.png)

It probably has to do with the `id="map"` restricting how the map can be placed on the page.

In general, it's helpful to have more flexibility with placing the map, in case we re-structure the page. Specifically for Bootstrap, in order for objects to be placed properly in the [Bootstrap grid system](https://getbootstrap.com/docs/4.1/layout/grid/), they should be organized in rows and columns inside of containers. For the map, this means it would at least need to be moved one `div` below the `container` div. If I do this (with or without the `main` tags), I get no map again:

```html
    <!-- Map -->
    <div class="container">
      <div id="map"></div>
    </div>
  <!-- TODO: close main tag here -->
```

I've been playing around with the code locally, but haven't really made progress fixing the issue. Could you try to replicate the issue, to make sure it's not anything with my local machine?

**Comment by AbdouSeck** [comment]
@br3ndonland glad you found out about this, because I gave up on trying to fix it on day one. This is, indeed, something that has to do with the google maps API. The latter brings its own `css` and `js` tweaks to the DOM, therefore dictating where and how to render the map. I've been looking for solutions for this for a while. I'll get it fixed once I figure it out.

**Comment by br3ndonland** [comment]
Great @AbdouSeck . No hurry on this, as it's more of an aesthetic issue than a functional one right now.

**Thanks for all your hard work. You're really driving progress of this project!**

**Comment by AbdouSeck** [comment]
This has been a great learning experience for me, so I am happy to be working on some of these questions.

**Comment by br3ndonland** [comment]
I figured out the solution to this issue, and will be happy to implement it. We'll revisit the front-end page structure after rebuilding the back-end.

The Google Maps JavaScript API docs don't explain how to nest the map div. I went back through the [overview](https://developers.google.com/maps/documentation/javascript/tutorial) and thought carefully about each step. The Map DOM Elements section says:

>Map DOM Elements
>
>```html
><div id="map"></div>
>```
>
>For the map to display on a web page, we must reserve a spot for it. Commonly, we do this by creating a named div element and obtaining a reference to this element in the browser's document object model (DOM).
>
>In the example above, we used CSS to set the height of the map div to "100%". This will expand to fit the size on mobile devices. You may need to adjust the width and height values based on the browser's screensize and padding. Note that divs usually take their width from their containing element, and empty divs usually have 0 height. For this reason, you must always set a height on the `<div>` explicitly.

Google clearly explains that `<div id="map"></div>` requires a CSS `height` style attribute. **Google doesn't explain that any `div` enclosing the map must also have its height set with CSS.** In the past, when I nested the map `div` within `main`, the map would disappear. When I set a height attribute for `main`, the map reappears.

**Comment by br3ndonland** [comment]
Map div successfully nested within HTML main tag through PR #40.
