### ISSUE TITLE
Name the app

### ISSUE THREAD

**Issue by br3ndonland** [growwithgooglema/mbtaccess#30]
# Name the app

## Current name

We should consider a name for our app. So far, we've had:

- **gwg-mbta**: Just a quick name I came up with for the repo.
- **GWG MAps**: I used this name as a placeholder when adding some front-end design features.
- **MBTA Find**:  Suggested by @noirfatale in her logo design.

## Suggestions

I think we should have a concise, unique name that highlights the wheelchair accessibility features of our app.

Here are two I thought of:

- **MBTAccess**
- **AccessMBTA**

I like **MBTAccess** best, but would welcome suggestions from others.

**Comment by AbdouSeck** [comment]
**MBTAccess** does sound pretty good to me.

**Comment by jethridge13** [comment]
My favorite from the list of options is **MBTAccess**.

**Comment by br3ndonland** [comment]
Thanks guys! @growwithgooglema/gwg-mbta , please weigh in over the next few days if you have opinions or new suggestions.

**Comment by br3ndonland** [comment]
We settled on the name **MBTAccess** in our [meeting on July 15 2018](https://github.com/orgs/growwithgooglema/teams/mbtaccess/discussions/6).
