### ISSUE TITLE
Add templating

### ISSUE THREAD

**Issue by br3ndonland** [growwithgooglema/mbtaccess#37]
# Add templating

## Current behavior

The app currently has two separate pages, the map page and the university list page. Right now, the map and university pages have different headers, accidentally. Templating will allow us to use a common page layout.

## Suggested behavior

- After improving speed on the back-end (see #36 ), we will remodel the front-end with templating.
- We're considering:
  - Flask/Jinja if we want to template through Python. This could be the best option if we build a Python back-end. Jinja can be slow if functions are included in the templates.
  - Jekyll if we want to stick with GitHub Pages.
  - Vue.js or React Router for templating on the front-end with JavaScript. If templating with VueJS and building our own back-end API, we could pipe in our API to the front-end.

**Comment by br3ndonland** [comment]
I have created Flask page templates, and will submit a pull request from the `flaskifying` branch once pull request #39 has been reviewed and accepted.

**Comment by AbdouSeck** [comment]
Can I do some nitpicking and recommend the creation of a new branch for templating? I am trying to avoid potential conflicts with both of us making edits within the same branch. If you've already started working in the branch, I will wait until you've submitted all your changes to make any new edits.

**Comment by br3ndonland** [comment]
Sure thing @AbdouSeck . Should I make a new branch off of `flaskifying` or `dev`? Either way, I'll be sure to submit a pull request before merging.

**Comment by AbdouSeck** [comment]
@br3ndonland I would recommend making a branch from the `dev` branch after `flaskifying` has been merged. I just pushed minor edits to the `flaskifying` branch, so if you like, you can merge it to the `dev` branch before making your own branch. Sorry about the delay in getting back to you. I am also going to write unit tests for `app.py` and `utilities.py` tonight.

I will only be working from the `flaskifying` branch and using `dev` as a base.

Thanks,

Abdou

**Comment by br3ndonland** [comment]
Sounds great @AbdouSeck . I'll branch off of `dev` after we merge in `flaskifying` from PR #39 .

It was great that you requested reviews on PR #39 . I was thinking we could let @jethridge13 merge PR #39 once he has a chance to test out the changes. It would be great to have his eyes on the new code as well. I'll follow up over Slack in the next day or two.

**Comment by br3ndonland** [comment]
Templates added with merge of PR #40.
